"""Failure reason codes used in Silver quality checks."""

COMPLETENESS_EMAIL = "COMPLETENESS_EMAIL"
COMPLETENESS_CUSTOMER_ID = "COMPLETENESS_CUSTOMER_ID"
COMPLETENESS_PRODUCT_ID = "COMPLETENESS_PRODUCT_ID"
COMPLETENESS_PRODUCT_NAME = "COMPLETENESS_PRODUCT_NAME"

UNIQUENESS_CUSTOMER_ID = "UNIQUENESS_CUSTOMER_ID"
UNIQUENESS_ORDER_ID = "UNIQUENESS_ORDER_ID"
UNIQUENESS_PRODUCT_ID = "UNIQUENESS_PRODUCT_ID"

TYPE_VALIDATION = "TYPE_VALIDATION"

RI_CUSTOMER = "RI_CUSTOMER"
RI_PRODUCT = "RI_PRODUCT"

CUSTOMER_SEGMENTS = ("Premium", "Standard", "Basic")
ORDER_STATUSES = ("Pending", "Completed", "Cancelled")
